# Generated by Django 4.2.4 on 2023-08-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcenter',
            name='endTiming',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='testcenter',
            name='startTiming',
            field=models.TimeField(),
        ),
    ]
